# Generated by Django 3.0.3 on 2020-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='mid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
