# Generated by Django 3.0.3 on 2020-02-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_motor_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='speed',
        ),
    ]
